# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-dev:
    environment: dev
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to private docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
        id: docker-tag
      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REPOSITORY }}:${{ steps.docker-tag.outputs.tag }}
            ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
      - name: Env substitute k8s
        uses: danielr1996/envsubst-action@1.0.0
        env:
            MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD_DEV }}
            JWT_SECRET: ${{ secrets.JWT_SECRET_DEV }}
            DOCKER_IMAGE: ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
        with:
          input: ci/k8s/dev.template.yaml
          output: ci/k8s/dev.yaml
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0
          command: apply -f ci/k8s/dev.yaml